[tool.poetry]
name = "flake8-pytest-style"
version = "0.0.0"
description = ""
authors = ["Mikhail Burshteyn <mdburshteyn@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/m-burst/flake8-pytest-style"
homepage = "https://pypi.org/project/flake8-pytest-style"
keywords = ["flake8", "pytest"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Environment :: Plugins",
  "Framework :: Flake8",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Quality Assurance",
]

[tool.poetry.plugins."flake8.extension"]
PT = 'flake8_pytest_style.plugin:PytestStylePlugin'

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = {version = "^19.3-beta.0",allows-prereleases = true}
bumpversion = "^0.5.3"
flake8-awesome = ">=0.2.0"
mypy = "^0.701.0"
pylint = "^2.2"
pytest = "^4.0"
pytest-cov = "^2.6"
pytest-deadfixtures = "^2.1"
pytest-mock = "^1.10"
unify = "^0.4.0"

[tool.black]
exclude = '_vendor'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
